# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: Xinchun Li # the website title (if blank, full name will be used instead)
first_name: Xinchun
middle_name: 
last_name: Li
email: lixch65@mail2.sysu.edu.cn
description: >
  Welcome! My research is rooted in computational communication, integrating in-depth qualitative methods. 
  I aim to transcend traditional quantitative paradigms, gaining micro-level insights into individual experiences 
  and emotional trajectories, to understand the complexity and resonance of human nature within social media emotion, 
  digital mourning, and online communities from a humanistic perspective. Feel free to explore my site to learn more 
  about my academic journey, and I look forward to connecting with you.
keywords: academic-website, portfolio-website, computational-communication, qualitative-research  # add your own keywords or leave empty

baseurl: "/chunwebsite"
url: "https://chunn20.github.io"


lang: en # the language of your site (for SEO)
icon: ⚛️  # the emoji used as the favicon (alternatively, provide image name in /assets/img/)

url: # the base hostname & protocol for your site
baseurl: # the subpath of your site, e.g. /blog/
last_updated: false # set to true if you want to display last updated in the footer
impressum_path:  # set to path to include impressum link in the footer, use the same path as permalink in a page, helps to conform with EU GDPR

# -----------------------------------------------------------------------------
# Theme
# -----------------------------------------------------------------------------

# repo color theme
repo_theme_light: default       # https://github.com/topics/jekyll-theme
repo_theme_dark: dark           # https://github.com/topics/jekyll-theme
repo_trophies:
  enabled: true
  theme_light: flat    # https://github.com/ryo-ma/github-profile-trophy
  theme_dark: gitdimmed  # https://github.com/ryo-ma/github-profile-trophy

# -----------------------------------------------------------------------------
# RSS Feed
# -----------------------------------------------------------------------------
# will use title and url fields
# Take a look to https://github.com/jekyll/jekyll-feed for more customization

rss_icon: true

# -----------------------------------------------------------------------------
# Layout
# -----------------------------------------------------------------------------

navbar_fixed: true
footer_fixed: true

# Dimensions
max_width: 800px

# -----------------------------------------------------------------------------
# Open Graph & Schema.org
# -----------------------------------------------------------------------------
# Display links to the page with a preview object on social media.
serve_og_meta: false # Include Open Graph meta tags in the HTML head
serve_schema_org: false # Include Schema.org in the HTML head
og_image: # The site-wide (default for all links) Open Graph preview image

# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------

github_username: Chunn20 # your GitHub user name
instagram_id: # your instagram id - reserved for future use
facebook_id: # your facebook id - reserved for future use
# All other social media accounts below are disabled
# gitlab_username: # your GitLab user name
# x_username: # your X handle
# mastodon_username: # your mastodon instance+username in the format instance.tld/@username
# linkedin_username: # your LinkedIn user name
# telegram_username: # your Telegram user name
# scholar_userid: # your Google Scholar ID
# semanticscholar_id: # your Semantic Scholar ID
# whatsapp_number: # your WhatsApp number
# orcid_id: # your ORCID ID
# medium_username: # your Medium username
# quora_username: # your Quora username
# publons_id: # your ID on Publons
# lattes_id: # your ID on Lattes
# osf_id: # your OSF ID
# research_gate_profile: # your profile on ResearchGate
# scopus_id: # your profile on Scopus
# blogger_url: # your blogger URL
# work_url: # work page URL
# keybase_username: # your keybase user name
# wikidata_id: # your wikidata id
# wikipedia_id: # your wikipedia id
# dblp_url: # your DBLP profile url
# stackoverflow_id: # your stackoverflow id
# kaggle_id: # your kaggle id
# lastfm_id: # your lastfm id
# spotify_id: # your spotify id
# pinterest_id: # your pinterest id
# unsplash_id: # your unsplash id
# youtube_id: # your youtube channel id
# discord_id: # your discord id
# zotero_username: # your zotero username
#google_analytics:  # your Google Analytics measurement ID (G-XXXXXXXXXX)

contact_note: >
  Feel free to reach out to me via email or GitHub.

# -----------------------------------------------------------------------------
# Buttons
# -----------------------------------------------------------------------------

contact_button: Contact Me
contact_button_url: /contact/
cv_button: Download CV
cv_button_url: /assets/pdf/Xin_chun_s_Resume.pdf

# -----------------------------------------------------------------------------
# Navigation bar
# -----------------------------------------------------------------------------

nav_item:
  - title: Home
    url: /
  - title: About Me
    url: /aboutme/
  - title: Research
    url: /research/
  - title: Blog
    url: /blog/
  - title: Contact
    url: /contact/

# -----------------------------------------------------------------------------
# Bilingual Setup
# -----------------------------------------------------------------------------

default_lang: en
languages:
  - en
  - zh

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------

collections:
  news:
    defaults:
      layout: post
    output: true
    permalink: /news/:path/
  projects:
    output: true
    permalink: /projects/:path/
  talks:
    output: true
    permalink: /talks/:path/

announcements:
  enabled: false
  scrollable: true # adds a vertical scroll bar if there are more than 3 news items
  limit: 5 # leave blank to include all the news in the `_news` folder

latest_posts:
  enabled: true
  scrollable: true # adds a vertical scroll bar if there are more than 3 new posts items
  limit: 3 # leave blank to include all the blog posts

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Markdown and syntax highlight
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

# Includes & excludes
include: ['_pages']
exclude:
  - bin
  - Gemfile
  - Gemfile.lock
  - vendor
keep_files:
  - CNAME
  - .nojekyll
  - .git

# Plug-ins
plugins:
  - jekyll-archives
  - jekyll-diagrams
  - jekyll-email-protect
  - jekyll-feed
  - jekyll-get-json
  - jekyll-imagemagick
  - jekyll-jupyter-notebook
  - jekyll-link-attributes
  - jekyll-minifier
  - jekyll-paginate-v2
  - jekyll/scholar
  - jekyll-sitemap
  - jekyll-toc
  - jekyll-twitter-plugin
  - jemoji

# Sitemap settings
defaults:
  - scope:
      path: "assets"
    values:
      sitemap: false

# -----------------------------------------------------------------------------
# Profile
# -----------------------------------------------------------------------------

profile:
  image: prof_pic.jpg
  address: >
    <p><a href="https://www.sysu.edu.cn">Sun Yat-sen University</a></p>
    <p>Guangzhou, China</p>

# -----------------------------------------------------------------------------
# Affiliations
# -----------------------------------------------------------------------------

affiliation: Master's Student, Sun Yat-sen University

# -----------------------------------------------------------------------------
# Jekyll Minifier
# -----------------------------------------------------------------------------

jekyll-minifier:
  exclude: ['robots.txt']
  uglifier_args:
    harmony: true

# -----------------------------------------------------------------------------
# Jekyll Archives
# -----------------------------------------------------------------------------

jekyll-archives:
  enabled: [year, tags, categories] # enables year, tag and category archives (remove if you need to disable one of them).
  layouts:
    year: archive-year
    tag: archive-tag
    category: archive-category
  permalinks:
    year: '/blog/:year/'
    tag: '/blog/tag/:name/'
    category: '/blog/category/:name/'

display_tags: ['computational-communication', 'digital-mourning', 'online-communities', 'qualitative-research'] # these tags will be displayed on the front page of your blog
display_categories: ['research-methods', 'digital-communication'] # these categories will be displayed on the front page of your blog

# -----------------------------------------------------------------------------
# Jekyll Scholar
# -----------------------------------------------------------------------------

scholar:

  last_name: [Li]
  first_name: [Xinchun]

  style: apa
  locale: en

  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: bib
  # Note: if you have latex math in your bibtex, the latex filter
  # preprocessing may conflict with MathJAX if the latter is enabled.
  # See https://github.com/alshedivat/al-folio/issues/357.
  bibtex_filters: [latex, smallcaps, superscript]

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"
  group_by: year
  group_order: descending

# Display different badges withs stats for your publications
enable_publication_badges:
  altmetric: true # Altmetric badge (https://www.altmetric.com/products/altmetric-badges/)
  dimensions: true # Dimensions badge (https://badge.dimensions.ai/)

# -----------------------------------------------------------------------------
# Jekyll Link Attributes
# -----------------------------------------------------------------------------

# These are the defaults
external_links:
  enabled: true
  rel: external nofollow noopener
  target: _blank
  exclude:


# -----------------------------------------------------------------------------
# Responsive WebP Images
# -----------------------------------------------------------------------------

imagemagick:
  enabled: false # enables responsive images for your site (recommended, see https://github.com/alshedivat/al-folio/issues/537)
  widths:
    - 480
    - 800
    - 1400
  input_directories:
    - assets/img/
  input_formats:
    - ".jpg"
    - ".jpeg"
    - ".png"
    - ".tiff"
  output_formats:
    webp: "-resize 800x"

# -----------------------------------------------------------------------------
# Jekyll Diagrams
# -----------------------------------------------------------------------------

jekyll-diagrams:
    # configuration, see https://github.com/zhustec/jekyll-diagrams.
    # feel free to comment out this section if not using jekyll diagrams.


# -----------------------------------------------------------------------------
# Optional Features
# -----------------------------------------------------------------------------

enable_google_analytics:    false  # enables google analytics
enable_cronitor_analytics: false  # enables cronitor RUM analytics
enable_google_verification: false  # enables google site verification
enable_bing_verification:   false  # enables bing site verification
enable_masonry:             true   # enables automatic project cards arrangement
enable_math:                true   # enables math typesetting (uses MathJax)
enable_tooltips:            false  # enables automatic tooltip links generated
                                   # for each section titles on pages and posts
enable_darkmode:            true   # enables switching between light/dark modes
enable_navbar_social:       false  # enables displaying social links in the
                                   # navbar on the about page
enable_project_categories:  true   # enables categorization of projects into
                                   # multiple categories
enable_medium_zoom:         true   # enables image zoom feature (as on medium.com)
enable_progressbar:         true   # enables a horizontal progress bar linked to the vertical scroll position

# -----------------------------------------------------------------------------
# Library versions
# -----------------------------------------------------------------------------

# Add the url, version and integrity hash of the libraries you use in your site.
# The integrity hash is used to ensure that the library is not tampered with.
# Integrity hashes not provided by the libraries were generated using https://www.srihash.org/
third_party_libraries:
  download: false # if true, download the versions of the libraries specified below and use the downloaded files
  bootstrap-table:
    integrity:
      css: "sha256-uRX+PiRTR4ysKFRCykT8HLuRCub26LgXJZym3Yeom1c="
      js: "sha256-4rppopQE9POKfukn2kEvhJ9Um25Cf6+IDVkARD0xh78="
    url:
      css: "https://cdn.jsdelivr.net/npm/bootstrap-table@{{version}}/dist/bootstrap-table.min.css"
      js: "https://cdn.jsdelivr.net/npm/bootstrap-table@{{version}}/dist/bootstrap-table.min.js"
    version: "1.22.1"
  jquery:
    integrity:
      js: "sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
    url:
      js: "https://cdn.jsdelivr.net/npm/jquery@{{version}}/dist/jquery.min.js"
    version: "3.6.0"
  mathjax:
    integrity:
      js: "sha256-MASABpB4tYktI2Oitl4t+78w/lyA+D7b/s9GEP0JOGI="
    url:
      js: "https://cdn.jsdelivr.net/npm/mathjax@{{version}}/es5/tex-mml-chtml.js"
    version: "3.2.0"
  masonry:
    integrity:
      js: "sha256-Nn1q/fx0H7SNLZMQ5Hw5JLaTRZp0yILA/FRexe19VdI="
    url:
      js: "https://cdn.jsdelivr.net/npm/masonry-layout@{{version}}/dist/masonry.pkgd.min.js"
    version: "4.2.2"
  mdb:
    integrity:
      css: "sha256-jpjYvU3G3N6nrrBwXJoVEYI/0zw8htfFnhT9ljN3JJw="
      js: "sha256-NdbiivsvWt7VYCt6hYNT3h/th9vSTL4EDWeGs5SN3DA="
    url:
      css: "https://cdn.jsdelivr.net/npm/mdbootstrap@{{version}}/css/mdb.min.css"
      js: "https://cdn.jsdelivr.net/npm/mdbootstrap@{{version}}/js/mdb.min.js"
    version: "4.20.0"
  medium_zoom:
    integrity:
      js: "sha256-7PhEpEWEW0XXQ0k6kQrPKwuoIomz8R8IYyuU1Qew4P8="
    url:
      js: "https://cdn.jsdelivr.net/npm/medium-zoom@{{version}}/dist/medium-zoom.min.js"
    version: "1.0.8"

bootstrap-table:
  version: "1.22.1"
jquery:
  version: "3.6.0"
  integrity: "sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
mathjax:
  version: "3.2.0"
masonry:
  version: "4.2.2"
  integrity: "sha256-Nn1q/fx0H7SNLZMQ5Hw5JLaTRZp0yILA/FRexe19VdI="
mdb:
  version: "4.20.0"
  integrity:
    css: "sha256-jpjYvU3G3N6nrrBwXJoVEYI/0zw8htfFnhT9ljN3JJw="
    js: "sha256-NdbiivsvWt7VYCt6hYNT3h/th9vSTL4EDWeGs5SN3DA="
medium_zoom:
  version: "1.0.8"
  integrity: "sha256-7PhEpEWEW0XXQ0k6kQrPKwuoIomz8R8IYyuU1Qew4P8="

# -----------------------------------------------------------------------------
# Get external JSON data
# -----------------------------------------------------------------------------

jekyll_get_json:
  - data: resume
    json: assets/json/resume.json # it can also be an url
jsonresume:
  - basics
  - work
  - education
  - publications
  - projects
  - volunteer
  - awards
  - certificates
  - skills
  - languages
  - interests
  - references
