name: Deploy with Docker

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Docker
        uses: docker/setup-buildx-action@v3

      - name: Prepare .jekyll-cache directory
        run: mkdir -p .jekyll-cache && chmod 777 .jekyll-cache

      - name: Prepare .tweet-cache directory
        run: mkdir -p .tweet-cache && chmod 777 .tweet-cache

      - name: Remove and recreate _site directory
        run: |
          sudo rm -rf _site .jekyll-cache .tweet-cache
          mkdir -p _site .jekyll-cache .tweet-cache
          chmod -R 777 _site .jekyll-cache .tweet-cache

      - name: Build Jekyll site (with Jupyter)
        run: |
          docker run --rm \
            --user root \
            --volume="${PWD}:/srv/jekyll" \
            jekyll/jekyll:4.2.2 \
            sh -c "apk add --no-cache python3 py3-pip python3-dev build-base linux-headers libffi-dev openssl-dev && pip3 install --upgrade --ignore-installed packaging && pip3 install jupyter && bundle install --frozen && jekyll build --config _config.yml,_config_prod.yml"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages

      - name: Preview Jekyll site
        run: bundle exec jekyll serve --config _config.yml,_config_prod.yml

      - name: Check git status
        run: git status

      - name: Add all pages
        run: git add .

      - name: Commit all pages
        run: git commit -m "add all pages"

      - name: Push all pages
        run: git push 