name: Deploy with Docker

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Docker
        uses: docker/setup-buildx-action@v3

      - name: Prepare .jekyll-cache directory
        run: mkdir -p .jekyll-cache && chmod 777 .jekyll-cache

      - name: Prepare .tweet-cache directory
        run: mkdir -p .tweet-cache && chmod 777 .tweet-cache

      - name: Build Jekyll site
        run: |
          docker run --rm \
            --user root \
            --volume="${PWD}:/srv/jekyll" \
            jekyll/jekyll:4.2.2 \
            bash -c "bundle install --frozen && jekyll build"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages 