name: Deploy with Docker

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Jekyll site
        run: |
          docker run --rm \
            --volume="${PWD}:/srv/jekyll:Z" \
            --volume="${PWD}/_site:/srv/jekyll/_site:Z" \
            jekyll/jekyll:4.3.2 \
            jekyll build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages 